---
platform: linux

inputs:
  - name: config
  - name: env # contains the env file with target OpsMan Information
outputs:
  - name: backup
    # This will output a *.tgz of the entire backup.
    # The filename includes the timestamp.


params:
  ENV_FILE: env.yml
  # - Required
  # - Filepath of the env config YAML
  # - The path is relative to the root of the `env` input

  DEPLOYMENT_NAME:
  # - Required
  # - The name of the product config to be exported

  OPSMAN_SSH_PRIVATE_KEY:
  # - Optional
  # - May be required to communicate with the Ops Manager BOSH director
  # - This is the private key for the Ops Manager VM (used during VM creation)

  OPSMAN_SSH_USERNAME: ubuntu
  # - Optional
  # - May be required to communicate with the Ops Manager BOSH director
  # - This is the username used when tunneling through the Ops Manager VM

run:
  path: config/ci/tasks/backup-deployment/backup-deployment.sh