---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: developer-cluster-role-binding
  namespace: my-namespace
subjects:
  - kind: User
    name: oidc:my-ldap-username
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: oidc:my-ldap-group-name
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: developer
  apiGroup: rbac.authorization.k8s.io